parameters:
  adldap2.class: Adldap2Bundle\Controller\Adldap2Controller
  adldap2user.class: Adldap2Bundle\Controller\Adldap2UserController
  adldap2ou.class: Adldap2Bundle\Controller\Adldap2OUController
  adldap2container.class: Adldap2Bundle\Controller\Adldap2ContainerController
  adldap2group.class: Adldap2Bundle\Controller\Adldap2GroupController

services:
  adldap2:
    class: "%adldap2.class%"
    arguments: ["@kernel"]
  adldap2user:
    class: "%adldap2user.class%"
    arguments: ["@kernel"]
  adldap2ou:
    class: "%adldap2ou.class%"
    arguments: ["@kernel"]
  adldap2container:
    class: "%adldap2container.class%"
    arguments: ["@kernel"]
  adldap2group:
    class: "%adldap2group.class%"
    arguments: ["@kernel"]
    #tags:
    #    - { name: twig.extension }
